on:
  workflow_dispatch:
    inputs:
      username:
        description: "TikTok Username"
        required: true
        default: "pierreminiggio"
name: Get videos
jobs:
  get:
    name: Get videos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # in this example, there is a newer version already installed, 3.7.7, so the older version will be downloaded
        python-version: ['3.8']
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-python@v2
      - run: sudo apt update
      - run: sudo apt-get install libegl1 libopus0 libwoff1 libharfbuzz-icu0 gstreamer1.0-plugins-base libgstreamer-gl1.0-0 gstreamer1.0-plugins-bad libopenjp2-7 libwebpdemux2 libenchant1c2a libhyphen0 libgles2 gstreamer1.0-libav
      - run: echo $username
        env:
          username: ${{ github.event.inputs.username }}
      - run: pip install TikTokApi
      - run: python -m playwright install
      - run: echo "from TikTokApi import TikTokApi; import json;  api = TikTokApi(); n_videos = 20; username = '$username'; user_videos = api.byUsername(username, count=n_videos); print(json.dumps(user_videos))" | python > videos.json
        env:
          username: ${{ github.event.inputs.username }}
      - uses: actions/upload-artifact@v2
        with:
          name: videos.json
          path: videos.json
